### PR TITLE
fix: fix show commitment response by adding a raw response to see if value were omitted

### PR DESCRIPTION
**Pull request by politeWall**

### CODE REVIEW

**Comment by cosmic-vagabond** [comment]
@politeWall please share test results

**Comment by politeWall** [comment]
> @politeWall please share test results

Unit-Test added

**Review by Wgil — CHANGES_REQUESTED** [review]
Lets hold this branch until we sync.

**Comment by Wgil** [comment]
Since there's a new chain upgrade that changed these fields, we discussed that we will leave this on hold until the upgrade is done and then we will integrate the test.

**Comment by politeWall** [comment]
the query work with manual testing:

```sh
elysd q --output json --node "tcp://localhost:26657" wasm contract-state smart "elys17p9rzwnnfxcjp32un9ug7yhhzgtkhvl9jfksztgw5uh69wac2pgs98tvuy" '{
        "commitment_vesting_info": {
            "address": "elys16e9j5rwts6u7ss0te7s8zlzt92932sdk9sfs4x"
        }
    }' | jq
```

```json
{
  "data": {
    "vesting": {
      "amount": "28",
      "usd_amount": "0.0005280310550893"
    },
    "vesting_details": [
      {
        "id": "0",
        "total_vesting": {
          "amount": "14",
          "usd_amount": "0.00026401552754465"
        },
        "claimed": {
          "amount": "0",
          "usd_amount": "0"
        },
        "vested_so_far": {
          "amount": "0",
          "usd_amount": "0"
        },
        "remaining_blocks": 1554989
      },
      {
        "id": "1",
        "total_vesting": {
          "amount": "14",
          "usd_amount": "0.00026401552754465"
        },
        "claimed": {
          "amount": "0",
          "usd_amount": "0"
        },
        "vested_so_far": {
          "amount": "0",
          "usd_amount": "0"
        },
        "remaining_blocks": 1554994
      }
    ]
  }
}
```

**Review by cosmic-vagabond — APPROVED** [review]

**Pull request merged**
