### PR TITLE
feat: add query request for leverage LP

### PR DESCRIPTION
**Pull request by politeWall**
## query added at this PR: 
* https://github.com/elys-network/bindings/pull/221

## Query Status
* ✅ LeveragelpParams
* ✅LeveragelpQueryPositions
* ✅LeveragelpQueryPositionsByPool
* ✅LeveragelpGetStatus
* ✅LeveragelpQueryPositionsForAddress
* ✅LeveragelpGetWhitelist
* ✅LeveragelpIsWhitelisted
* ✅LeveragelpPool
* ✅LeveragelpPools
* ✅LeveragelpPosition

## Execute Status
* ✅LeveragelpOpen
* ✅LeveragelpClose

## Emoji Legend
* ✅ Query Working.
* ❌ Query Creating an Error
* ⏳ Not Tested Yet.

### CODE REVIEW

**Comment by politeWall** [comment]
##LeveragelpParams
```
$ elysd q --output json --node "tcp://localhost:26657" wasm contract-state smart "elys1nc5tatafv6eyq7llkr2gv50ff9e22mnf70qgjlv737ktmt4eswrqau4f4q" '{
        "leveragelp_params": {}
    }' | jq
```
```json
{
  "data": {
    "params": {
      "leverage_max": "10",
      "max_open_positions": 9999,
      "pool_open_threshold": "0.2",
      "safety_factor": "0.1",
      "whitelisting_enabled": false,
      "epoch_length": 1
    }
  }
}
```

**Comment by politeWall** [comment]
## LeveragelpQueryPositions
```
elysd q --output json --node "tcp://localhost:26657" wasm contract-state smart "elys1nc5tatafv6eyq7llkr2gv50ff9e22mnf70qgjlv737ktmt4eswrqau4f4q" '{
        "leveragelp_query_positions": {}
    }' | jq
```
```
Error: rpc error: code = Unknown desc = Error calling the VM: Error executing Wasm: Wasmer runtime error: RuntimeError: Error calling into the VM's backend: Panic in FFI call: query wasm contract failed: unknown request
```

**Comment by politeWall** [comment]
## LeveragelpQueryPositionsByPool
```
elysd q --output json --node "tcp://localhost:26657" wasm contract-state smart "elys1nc5tatafv6eyq7llkr2gv50ff9e22mnf70qgjlv737ktmt4eswrqau4f4q" '{
        "leveragelp_query_positions_by_pool": {
           "amm_pool_id" : 1 
        }
    }' | jq
```
```json
{
  "data": {
    "positions": [],
    "pagination": {
      "next_key": null,
      "total": null
    }
  }
}
```

**Comment by politeWall** [comment]
## LeveragelpGetStatus
```
elysd q --output json --node "tcp://localhost:26657" wasm contract-state smart "elys1nc5tatafv6eyq7llkr2gv50ff9e22mnf70qgjlv737ktmt4eswrqau4f4q" '{
        "leveragelp_get_status": {}
    }' | jq
```
```json
{
  "data": {
    "open_position_count": 1,
    "lifetime_position_count": 1
  }
}
```

**Comment by politeWall** [comment]
## LeveragelpGetWhitelist

```
elysd q --output json --node "tcp://localhost:26657" wasm contract-state smart "elys1nc5tatafv6eyq7llkr2gv50ff9e22mnf70qgjlv737ktmt4eswrqau4f4q" '{
        "leveragelp_get_whitelist": {}
    }' | jq
```
```
Error: rpc error: code = Unknown desc = Error calling the VM: Error executing Wasm: Wasmer runtime error: RuntimeError: Error calling into the VM's backend: Panic in FFI call: query wasm contract failed: unknown request
```

**Comment by politeWall** [comment]
## LeveragelpPools
```
elysd q --output json --node "tcp://localhost:26657" wasm contract-state smart "elys1qg5ega6dykkxc307y25pecuufrjkxkaggkkxh7nad0vhyhtuhw3s7zzmns" '{
        "leveragelp_pools": {}
    }'
```
```json
{
  "data": {
    "pool": [
      {
        "amm_pool_id": 2,
        "health": "0.997483648772789742",
        "enabled": true,
        "closed": false,
        "leveraged_lp_amount": "360796443087948623184",
        "leverage_max": "10"
      }
    ],
    "pagination": {
      "next_key": null,
      "total": 1
    }
  }
}
```

**Comment by politeWall** [comment]
## LeveragelpPool
```
elysd q --output json --node "tcp://localhost:26657" wasm contract-state smart "elys1qg5ega6dykkxc307y25pecuufrjkxkaggkkxh7nad0vhyhtuhw3s7zzmns" '{
        "leveragelp_pool": {
            "index": 2
        }
    }'
```
```json
{
  "data": {
    "pool": {
      "amm_pool_id": 2,
      "health": "0.997483648772789742",
      "enabled": true,
      "closed": false,
      "leveraged_lp_amount": "360796443087948623184",
      "leverage_max": "10"
    }
  }
}
```

**Comment by politeWall** [comment]
## LeveragelpIsWhitelisted

```
elysd q --output json --node "tcp://localhost:26657" wasm contract-state smart "elys1qg5ega6dykkxc307y25pecuufrjkxkaggkkxh7nad0vhyhtuhw3s7zzmns" '{
        "leveragelp_is_whitelisted": {
           "address" : "elys1myzulqh75uxxa73tf2z29hjrg95zypqq3pswn0"
        }
    }'
```

```json
{
  "data": {
    "address": "elys1myzulqh75uxxa73tf2z29hjrg95zypqq3pswn0",
    "is_whitelisted": false
  }
}
```

**Comment by politeWall** [comment]
## LeveragelpPosition
```
elysd q --output json --node "tcp://localhost:26657" wasm contract-state smart "elys1nc5tatafv6eyq7llkr2gv50ff9e22mnf70qgjlv737ktmt4eswrqau4f4q" '{
        "leveragelp_position": {
            "address" : "elys1lecaqfwf3edehsuukd56mdse66f098y02nzjsf",
            "id": 2
        }
    }'
```
```json
{
  "data": {
    "position": {
      "address": "elys1lecaqfwf3edehsuukd56mdse66f098y02nzjsf",
      "collateral": {
        "denom": "ibc/2180E84E20F5679FCC760D8C165B60F42065DEF7F46A72B447CFF1B7DC6C0A65",
        "amount": "10000000"
      },
      "liabilities": "40000000",
      "interest_paid": "0",
      "leverage": "5",
      "leveraged_lp_amount": "41343208402535017043",
      "position_health": "1.24266825",
      "id": 2,
      "amm_pool_id": 2,
      "stop_loss_price": "0"
    }
  }
}
```

**Comment by politeWall** [comment]
## LeveragelpQueryPositionsForAddress

```
elysd q --output json --node "tcp://localhost:26657" wasm contract-state smart "elys1nc5tatafv6eyq7llkr2gv50ff9e22mnf70qgjlv737ktmt4eswrqau4f4q" '{
        "leveragelp_query_positions_for_address": {
           "address" : "elys1lecaqfwf3edehsuukd56mdse66f098y02nzjsf"
        }
    }'
```
```json
{
  "data": {
    "positions": [
      {
        "address": "elys1lecaqfwf3edehsuukd56mdse66f098y02nzjsf",
        "collateral": {
          "denom": "ibc/2180E84E20F5679FCC760D8C165B60F42065DEF7F46A72B447CFF1B7DC6C0A65",
          "amount": "10000000"
        },
        "liabilities": "40000000",
        "interest_paid": "0",
        "leverage": "5",
        "leveraged_lp_amount": "41343208402535017043",
        "position_health": "1.24266825",
        "id": 2,
        "amm_pool_id": 2,
        "stop_loss_price": "0"
      }
    ],
    "pagination": {
      "next_key": null,
      "total": null
    }
  }
}
```

**Comment by politeWall** [comment]
## LeveragelpOpen
```sh
elysd tx wasm exec --from "validator" --keyring-backend test --node "tcp://localhost:26657" --chain-id elystestnet-1 --gas auto --gas-adjustment=1.3 --fees 100000uelys -b sync -y "elys1nc5tatafv6eyq7llkr2gv50ff9e22mnf70qgjlv737ktmt4eswrqau4f4q" '{
            "leveragelp_open": {
                "amm_pool_id": 2,
                "collateral_asset": "ibc/2180E84E20F5679FCC760D8C165B60F42065DEF7F46A72B447CFF1B7DC6C0A65",
                "collateral_amount": "10000000",
                "leverage": "5.0",
                "stop_loss_price": "0.0"
            }
        }'
```

### Query the position
```sh
elysd q --output json --node "tcp://localhost:26657" wasm contract-state smart "elys1nc5tatafv6eyq7llkr2gv50ff9e22mnf70qgjlv737ktmt4eswrqau4f4q" '{
        "leveragelp_query_positions_for_address": {
           "address" : "elys1pszy7cq5xhx6dvu082nvyjjd2q6mln9n3k5ly0"
        }
    }' | jq
```
```json
{
  "data": {
    "positions": [
      {
        "address": "elys1pszy7cq5xhx6dvu082nvyjjd2q6mln9n3k5ly0",
        "collateral": {
          "denom": "ibc/2180E84E20F5679FCC760D8C165B60F42065DEF7F46A72B447CFF1B7DC6C0A65",
          "amount": "20000000"
        },
        "liabilities": "80000000",
        "interest_paid": "0",
        "leverage": "5",
        "leveraged_lp_amount": "107894582318044847896",
        "position_health": "1.249209525948568862",
        "id": 2,
        "amm_pool_id": 2,
        "stop_loss_price": "0"
      }
    ],
    "pagination": {
      "next_key": null,
      "total": null
    }
  }
}
```

**Review by cosmic-vagabond — APPROVED** [review]

**Pull request merged**
