### PR TITLE
feat: add masterchef pending rewards

### PR DESCRIPTION
**Pull request by cryptokage1996**
https://trello.com/c/x9j85B2o

added querier function to fetch masterchef claim rewards

https://trello.com/c/I2KeI9NW

add masterchef pending rewards query function

### CODE REVIEW

**Review by Wgil — CHANGES_REQUESTED** [review]
Same here please, lets add this to account history contract

**Comment by Wgil** [comment]
@cryptokage2306 `get_masterchef_pending_rewards` response doesn't seem suitable for this as there can be more than one coin reward per pool:

```
{
  "rewards": {
    "2": {
      "denom": "ueden",
      "amount_token": "0.108389",
      "price": "18.418411450572793553",
      "amount_usd": "1.99635319871613452"
    },
    "3": {
      "denom": "ueden",
      "amount_token": "0.284951",
      "price": "18.418411450572793553",
      "amount_usd": "5.248344761252168095"
    },
    "5": {
      "denom": "ueden",
      "amount_token": "0.000198",
      "price": "18.418411450572793553",
      "amount_usd": "0.003646845467213413"
    },
    "32767": {
      "denom": "ueden",
      "amount_token": "0.240046",
      "price": "18.418411450572793553",
      "amount_usd": "4.421265995064196801"
    }
  },
  "total_rewards": [
    {
      "denom": "ibc/2180E84E20F5679FCC760D8C165B60F42065DEF7F46A72B447CFF1B7DC6C0A65",
      "amount_token": "1.287268",
      "price": "1.0001",
      "amount_usd": "1.2873967268"
    },
    {
      "denom": "ueden",
      "amount_token": "0.633584",
      "price": "18.418411450572793553",
      "amount_usd": "11.66961080049971283"
    }
  ]
}
```

Perhaps it's more suitable if you return it like this:
```
"2": [{
      "denom": "ueden",
      "amount_token": "0.108389",
      "price": "18.418411450572793553",
      "amount_usd": "1.99635319871613452"
    }, ...etc],
```

See the chain response, you're missing some records:

```
elysd q masterchef user-pending-reward elys1u8c28343vvhwgwhf29w6hlcz73hvq7lwxmrl46
rewards:
- pool_id: "2"
  reward:
  - amount: "198179"
    denom: ibc/2180E84E20F5679FCC760D8C165B60F42065DEF7F46A72B447CFF1B7DC6C0A65
  - amount: "132298"
    denom: ueden
- pool_id: "3"
  reward:
  - amount: "781474"
    denom: ibc/2180E84E20F5679FCC760D8C165B60F42065DEF7F46A72B447CFF1B7DC6C0A65
  - amount: "347807"
    denom: ueden
- pool_id: "4"
  reward: []
- pool_id: "5"
  reward:
  - amount: "362"
    denom: ibc/2180E84E20F5679FCC760D8C165B60F42065DEF7F46A72B447CFF1B7DC6C0A65
  - amount: "242"
    denom: ueden
- pool_id: "32767"
  reward:
  - amount: "307253"
    denom: ibc/2180E84E20F5679FCC760D8C165B60F42065DEF7F46A72B447CFF1B7DC6C0A65
  - amount: "292998"
    denom: ueden
total_rewards:
- amount: "1287268"
  denom: ibc/2180E84E20F5679FCC760D8C165B60F42065DEF7F46A72B447CFF1B7DC6C0A65
- amount: "773345"
  denom: ueden
```

**Comment by Wgil** [comment]
masterchef_claim_rewards is not working from this branch.

Screenshot 2024-04-29 at 10 06 26 AM

**Comment by Wgil** [comment]
@cryptokage2306 Also, I am able to deploy the contracts if I checkout commit [de005e5](https://github.com/elys-network/bindings/pull/296/commits/de005e557b26c2feaa391166c3e1d4f13f91acb6) but checking the latest code on branch gives this error:

```
Error: rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 0: Caught panic: create wasm contract failed [!cosm!wasm/wasmd@v0.41.0/x/wasm/keeper/keeper.go:177] With gas wanted: '18446744073709551615' and gas used: '6128959' : unknown request
```

**Comment by cryptokage2306** [comment]
Fixed from my side @Wgil
you can merge this PR

**Review by Wgil — APPROVED** [review]
LGTM

**Review by Wgil — APPROVED** [review]

**Pull request merged**
